// <auto-generated />
using System;
using App.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210421221601_01-initial")]
    partial class _01initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Domain.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("Date");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<decimal?>("Juros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Multa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Parcela")
                        .HasColumnType("int");

                    b.Property<int?>("idDocumentoOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("idDocumentoOrigem");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("App.Domain.Models.DocumentoBaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idDocumento");

                    b.ToTable("DocumentoBaixa");
                });

            modelBuilder.Entity("App.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("App.Domain.Models.Documento", b =>
                {
                    b.HasOne("App.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Documento", "DocumentoOrigem")
                        .WithMany()
                        .HasForeignKey("idDocumentoOrigem");

                    b.Navigation("DocumentoOrigem");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("App.Domain.Models.DocumentoBaixa", b =>
                {
                    b.HasOne("App.Domain.Models.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("idDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });
#pragma warning restore 612, 618
        }
    }
}
