// <auto-generated />
using System;
using App.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210424183118_01-inicial")]
    partial class _01inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Domain.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("Date");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<decimal?>("Juros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Multa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Parcela")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("idDocumentoOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("idDocumentoOrigem");

                    b.ToTable("Documentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 532, DateTimeKind.Unspecified).AddTicks(2535), new TimeSpan(0, -3, 0, 0, 0)),
                            DataVencimento = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPessoa = 1,
                            IdUsuarioInclusao = 0,
                            Juros = 0.01m,
                            Multa = 0.02m,
                            Parcela = 10,
                            TipoDocumento = 1,
                            Valor = 300m
                        },
                        new
                        {
                            Id = 2,
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 535, DateTimeKind.Unspecified).AddTicks(250), new TimeSpan(0, -3, 0, 0, 0)),
                            DataVencimento = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPessoa = 1,
                            IdUsuarioInclusao = 0,
                            Juros = 0.01m,
                            Multa = 0.02m,
                            Parcela = 10,
                            TipoDocumento = 2,
                            Valor = 100m,
                            idDocumentoOrigem = 1
                        },
                        new
                        {
                            Id = 3,
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 535, DateTimeKind.Unspecified).AddTicks(989), new TimeSpan(0, -3, 0, 0, 0)),
                            DataVencimento = new DateTime(2020, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPessoa = 1,
                            IdUsuarioInclusao = 0,
                            Juros = 0.01m,
                            Multa = 0.02m,
                            Parcela = 11,
                            TipoDocumento = 2,
                            Valor = 100m,
                            idDocumentoOrigem = 1
                        },
                        new
                        {
                            Id = 4,
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 535, DateTimeKind.Unspecified).AddTicks(1048), new TimeSpan(0, -3, 0, 0, 0)),
                            DataVencimento = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPessoa = 1,
                            IdUsuarioInclusao = 0,
                            Juros = 0.01m,
                            Multa = 0.02m,
                            Parcela = 12,
                            TipoDocumento = 2,
                            Valor = 100m,
                            idDocumentoOrigem = 1
                        },
                        new
                        {
                            Id = 5,
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 535, DateTimeKind.Unspecified).AddTicks(3793), new TimeSpan(0, -3, 0, 0, 0)),
                            DataVencimento = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPessoa = 2,
                            IdUsuarioInclusao = 0,
                            Juros = 0.01m,
                            Multa = 0.02m,
                            Parcela = 10,
                            TipoDocumento = 1,
                            Valor = 500m
                        });
                });

            modelBuilder.Entity("App.Domain.Models.DocumentoBaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataBaixa")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idDocumento");

                    b.ToTable("DocumentoBaixa");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            DataBaixa = new DateTimeOffset(new DateTime(2020, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 535, DateTimeKind.Unspecified).AddTicks(1677), new TimeSpan(0, -3, 0, 0, 0)),
                            IdUsuarioInclusao = 0,
                            Valor = 100m,
                            ValorDesconto = 0m,
                            idDocumento = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "12345678900",
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 526, DateTimeKind.Unspecified).AddTicks(1459), new TimeSpan(0, -3, 0, 0, 0)),
                            IdUsuarioInclusao = 0,
                            Nome = "Samuel de Moraes Lemes"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "11111111111",
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 532, DateTimeKind.Unspecified).AddTicks(355), new TimeSpan(0, -3, 0, 0, 0)),
                            IdUsuarioInclusao = 0,
                            Nome = "Jeremias de Moraes Lemes"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "22222222222",
                            DataInclusao = new DateTimeOffset(new DateTime(2021, 4, 24, 15, 31, 17, 532, DateTimeKind.Unspecified).AddTicks(518), new TimeSpan(0, -3, 0, 0, 0)),
                            IdUsuarioInclusao = 0,
                            Nome = "Patricia de Moraes Lemes"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Documento", b =>
                {
                    b.HasOne("App.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Documento", "DocumentoOrigem")
                        .WithMany()
                        .HasForeignKey("idDocumentoOrigem");

                    b.Navigation("DocumentoOrigem");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("App.Domain.Models.DocumentoBaixa", b =>
                {
                    b.HasOne("App.Domain.Models.Documento", "Documento")
                        .WithMany("Baixas")
                        .HasForeignKey("idDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("App.Domain.Models.Documento", b =>
                {
                    b.Navigation("Baixas");
                });
#pragma warning restore 612, 618
        }
    }
}
